name: MGWarlock
main: com.comze_instancelabs.mgwarlock.Main
version: 1.0.1
author: InstanceLabs
softdepend: [Vault, MinigamesAPI]
depend: [MinigamesAPI]
loadbefore: [MinigamesAPI]
commands:
   wl:
      description: Main command
      usage: /wl [action]
      aliases: [warlock, mgwarlock]
