name: MGWarlock
main: com.comze_instancelabs.mgwarlock.Main
version: ${minigames.releaseversion}-${minigames.timestamp}
author: [InstanceLabs,mepeisen]
softdepend: [Vault, MinigamesLib]
depend: [MinigamesLib]
loadbefore: [MinigamesLib]
commands:
   wl:
      description: Main command
      usage: /wl [action]
      aliases: [warlock, mgwarlock]
